### ISSUE TITLE
Wrong appearance on win7

### ISSUE THREAD

**Issue by jasonliul** [arctic-sun/apo#1]
![screenshot 1](https://user-images.githubusercontent.com/2461165/194604334-9aa31e4e-5a0f-47fd-8b27-b5391416897d.jpg)

Many items show nothing.

**Comment by arctic-sun** [comment]
Not tested on win7, thanks for the report, will be fixed in the next release

**Comment by arctic-sun** [comment]
Fixed in 0.1.2
