### ISSUE TITLE
Basilisk portable can't be process.

### ISSUE THREAD

**Issue by jasonliul** [arctic-sun/apo#2]
![6j2xst2h jpg](https://user-images.githubusercontent.com/2461165/194917353-3cfc2371-f755-4df5-a069-9c658a949fa9.jpg)
It's been listed in readme, and speedyfox do it well.

**Comment by arctic-sun** [comment]
there is no such portable version on the official website of the developer. Where did you get it ?

**Comment by arctic-sun** [comment]
Please check v0.1.6 i think it will work now.

**Comment by jasonliul** [comment]
https://portableapps.com/comment/241554#comment-241554
i use this method to make Basilisk portable, so also test Pale Moon 31.3.0.1,
both no working, strange.

**Comment by jasonliul** [comment]
i have no answer, so i deleted old profile, reset all config, now it's ok!
Thanks for your great effort, speedyfox can retire now.

p.s
Speedyfox has a function "save log", maybe you could add such feature.

**Comment by arctic-sun** [comment]
I want to note that if the path to the profile has Chinese symbols, then such a profile will not be processed. This will be fixed in the next version.

**Comment by jasonliul** [comment]
i never use Chinese symbols as path name, perhaps some reason corrupted my profile, so weird.
